/**
 * Generates docs/ASSET_CHECKLIST.md: every graphic and sound the game can use,
 * derived from the content packs (new characters/generators/cards appear
 * automatically) and marked ✅ when the file exists in apps/client/public/assets.
 *
 *   pnpm assets            # regenerate the checklist
 *   pnpm assets --check    # exit 1 if a required (non-optional) asset is missing
 */
import { existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { type AssetSpec, contentAssets, STATIC_ASSETS } from '../src/assets'
import { loadContentFromDisk } from './load-content'

const publicAssets = fileURLToPath(new URL('../../../apps/client/public/assets/', import.meta.url))
const out = fileURLToPath(new URL('../../../docs/ASSET_CHECKLIST.md', import.meta.url))

const content = loadContentFromDisk()
const all: AssetSpec[] = [...STATIC_ASSETS, ...contentAssets(content)]
const groups: Record<AssetSpec['kind'], string> = {
  sprite: 'Scene sprites',
  portrait: 'Character portraits',
  icon: 'Icons',
  illustration: 'Illustrations',
  audio: 'Audio',
}

let md = '# Asset checklist\n\n'
md += '> Generated by `pnpm assets` from the content packs — do not edit by hand.\n'
md += '> How to create and add assets: see [ASSET_GUIDE.md](ASSET_GUIDE.md).\n\n'
let done = 0
let missingRequired = 0
for (const [kind, title] of Object.entries(groups)) {
  const items = all.filter((a) => a.kind === kind)
  if (!items.length) continue
  md += `## ${title}\n\n| | File (under \`apps/client/public/assets/\`) | Size | Purpose |\n|---|---|---|---|\n`
  for (const a of items) {
    const exists = existsSync(publicAssets + a.path)
    if (exists) done++
    else if (!a.optional) missingRequired++
    md += `| ${exists ? '✅' : a.optional ? '⬜ optional' : '⬜'} | \`${a.path}\` | ${a.size} | ${a.purpose} |\n`
  }
  md += '\n'
}
md += `**Progress:** ${done} / ${all.length} files present, ${missingRequired} required still missing (placeholders are shown until then).\n`
writeFileSync(out, md)
console.log(
  `Wrote docs/ASSET_CHECKLIST.md — ${done}/${all.length} present, ${missingRequired} required missing.`,
)
if (process.argv.includes('--check') && missingRequired > 0) process.exit(1)
