import { Container, Graphics } from 'pixi.js'

/**
 * Last-resort fallback when a sprite file is missing entirely. The real
 * placeholders are pixel-art PNGs generated by `scripts/pixel-placeholders.mjs`
 * (see docs/ASSET_GUIDE.md). Anchored bottom-centre like every sprite.
 */
export function drawPlaceholder(_id: string, w = 32, h = 32): Container {
  const c = new Container()
  const g = new Graphics()
    .rect(-w / 2, -h, w, h)
    .fill(0x5a6988)
    .rect(-w / 2, -h, w, h)
    .stroke({ width: 1, color: 0x181425 })
  c.addChild(g)
  return c
}
